version: '3'

services:

  mysql-standalone:

    restart: always

    container_name: mysql-standalone

    image: mysql:5.6

    environment:

      MYSQL_DATABASE: test

      MYSQL_ROOT_PASSWORD: password
      
      MYSQL_USER: sa
      
      MYSQL_PASSWORD: password

      MYSQL_ROOT_HOST: '%'

    volumes:

      - ./sql:/docker-entrypoint-initdb.d


    ports:

      - "3306:3306"

#    healthcheck:
#
#      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
#
#      interval: 2s
#
#      timeout: 20s
#
#      retries: 10


  transaction:

    restart: on-failure

    container_name: transaction-mysql
    
    image: akshaypy/transaction-mysql:latest

    expose:

      - "8089"

    ports:

      - 8089:8089

    environment:

      WAIT_HOSTS: mysql:3306

    depends_on:

      - mysql-standalone